apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:

  #! Product release files
  - path: reveal.js-4.2.1
    contents:
      - path: .
        git:
          url: https://github.com/hakimel/reveal.js
          ref: 4.2.1
